    server:
        port: 8080
        servlet:
            session:
                timeout: 30
        ssl:
            enabled: false
            key-store: "/app/Gen_Web_API/cert/star_hmc_co_kr.jks"
            key-store-password: "w853kx7q"
            key-store-type: "JKS"

    genesysinfo: 
      cfg_ip_p: 10.10.61.29
      cfg_ip_b: 10.10.61.29
      cfg_port_p: 2020
      cfg_port_b: 2020
      cfg_endpoint_p: Cfg_EP_P 
      cfg_endpoint_b: Cfg_EP_B
      cfg_client_name: default
      cfg_tenant_dbid: 1
      cfg_switch_dbid: 101
      cfg_switch_dbid2: 0
      cfg_id: apiadm
      #cfg_passwd: ENC(aQJKA/qeRV9noXEeDGRLJ6jP7iIvn43K)
      cfg_passwd: apiadm
      cfg_charset: MS949
      oc_ip_p: 10.10.61.29
      oc_port_p: 2030
      oc_id: apiadm
      #oc_passwd: ENC(aQJKA/qeRV9noXEeDGRLJ6jP7iIvn43K)
      oc_passwd: apiadm
      oc_client_id: 
      oc_client_passwd: 
      oc_charset: MS949
      stat_ip_p: 10.10.61.29
      stat_port_p: 2032
      stat_ip_b: 10.10.61.29
      stat_port_b: 2032
      stat_charset: MS949
      stat_endpoint1: statserver_rtm
      stat_endpoint2: statserver_rtm
      stat_clientname: gps_stat
      stat_tenant: Environment
      stat_tenantdbid: 1
      stat_switch: Switch
      stat_frequency: 1
      stat_lastrefid: 679
      stat_delay: 30
      stat-timeout: 2000
      sc_ip_p: 10.10.61.29
      sc_ip_b: 10.10.61.29
      sc_port_p: 2024
      sc_port_b: 2024
      sc_endpoint_p: Sc_EP_P
      sc_endpoint_b: Sc_EP_B
      sc_client_name: i4way_GPS_1
      sc_id: apiadm 
      sc_tenant_dbid: 1
      sc_client_dbid: 106
      sc_charset: MS949
      sc_monitoring_dbids: 107,112,113,117,118,119
      t_ip_p: 10.10.61.56
      t_ip_b: 10.10.61.56
      t_port_p: 3000
      t_port_b: 3000
      t_endpoint_p: T_EP_P
      t_endpoint_b: T_EP_B
      t_client_name: i4way_GPS_1
      t_tenant_dbid: 1
      t_charset: MS949

    ccc-service:
      enc-iv: 1234567890123456
      enc-key: 12345678901234567890123456789012
      #Yes : Encrypt On, No : Encrypt Off
      #enc-yn: 'Yes'
      enc-yn: 'Yes'

    jasypt:
      encryptor:
        bean: jasyptStringEncryptor
        property:
          prefix: ENC(
          suffix: )          